github.com:
    users:
        aaryanahlawat:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: aaryanahlawat
